#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 10 10:34:06 2018

@author: lukas
"""



os.chdir('/home/lukas/Documents/projects/headSegmentation/deepMedicKeras/')

###################   parameters // replace with config files ########################


dataset = 'BRATS15'

usingLoadedData = False
allBatchesAddress = '/home/lukas/Documents/projects/headSegmentation/deepMedicKeras/allBatches.pkl'
allLabelsAddress =  '/home/lukas/Documents/projects/headSegmentation/deepMedicKeras/allLabels.pkl'
allValBatchesAddress = '/home/lukas/Documents/projects/headSegmentation/deepMedicKeras/allValBatches.pkl'
allValLabelsAddress = '/home/lukas/Documents/projects/headSegmentation/deepMedicKeras/allValLabels.pkl'

# Parameters // this could be assigned in separate configuration files

# MODEL PARAMETERS

dpatch=51
L2 = 0

# TRAIN PARAMETERS
num_iter = 20
epochs = 10
n_patches = 2000
n_patches_val = 2000
n_subjects = 50
samplingMethod = 1
size_minibatches = 200


# TEST PARAMETERS
list_subjects_fullSegmentation = [0,1,2]
epochs_for_fullSegmentation = [1,3,6,9]
size_test_minibatches = 200
saveSegmentation = True

load_model = False
